Unexpected revert with vector
CoinFabrik/scout-soroban pull request #150
Opened 2024-04-19 19:02 UTC by sofiazcoaga

2024-04-23 16:43 UTC, arturoBeccar requested changes
Vulnerable and remediated example should be located inside a numbered folder, allowing for new test cases to be added later.

Vulnerable and remediated example should be located inside the following path:

`test-cases/dos-unexpected-revert-with-vector/dos-unexpected-revert-with-vector-1`

Take as reference https://github.com/CoinFabrik/scout-soroban/tree/main/test-cases/assert-violation/assert-violation-1

2024-04-25 17:12 UTC, tenuki approved these changes

2024-04-25 17:14 UTC, tenuki commented
@sofiazcoaga revisa/resolve lo que hizo notar

2024-05-02 16:50 UTC, tenuki approved these changes

2024-05-02 17:04 UTC, merged