Events detectors
CoinFabrik/scout-soroban pull request #330
Opened 2024-08-20 18:11 UTC by sofiazcoaga

Includes: 

- Storage change events detector: emits a warning when storage is modified in any way and the contract does not emit an event. 
- Storage change events test cases. 
- Token Interface events detector: emits a warning when the token interface trait is implemented and the functions belonging to it that should emit events do not. 
- Token Interface events test cases.

2024-08-26 22:37 UTC, tenuki requested changes

2024-08-26 22:37 UTC, tenuki commented on test-cases/token-interface-events/token-interface-events-1/vulnerable-example/src/lib.rs
> +            .set(&DataKey::Balance(to), &(previous_balance + amount));
Esta función está modificando balances/ y no tira eventos.. y el detector de token-interface no dice nada y deberia, no?

2024-08-26 22:37 UTC, tenuki commented on test-cases/token-interface-events/token-interface-events-1/vulnerable-example/src/lib.rs
> +            .set(&DataKey::Balance(to), &(previous_balance + amount));
ver que es un evento definido en la TI : https://github.com/stellar/rs-soroban-sdk/blob/f57d2454e520ae11dc9c8d55db610557a24a556e/soroban-token-sdk/src/event.rs#L25C18-L25C22

2024-08-26 22:38 UTC, tenuki commented
sofi check the comments let us know whatever you thinkg about it..

2024-08-27 16:21 UTC, sofiazcoaga commented on test-cases/token-interface-events/token-interface-events-1/vulnerable-example/src/lib.rs
> +            .set(&DataKey::Balance(to), &(previous_balance + amount));
hecho

2024-08-28 22:34 UTC, tenuki approved these changes

2024-08-28 22:35 UTC, merged